#pragma once
#include "matrix.hpp"
#include <functional>
#include <vector>
#include <cassert>

// This block of code was generated by Chat GPT Instant 5.3

namespace pp {

inline vector lsfit(
	const std::vector <std::function<double(double)>>& fs,
	const vector& x,
	const vector& y,
	const vector& dy
){
	int n = x.size();
	int m = fs.size();

	assert(y.size() == n);
	assert(dy.size() == n);
	assert(n >= m);

	matrix A(n, m);
	vector b(n);

	for(int i = 0; i < n; i++){
		assert(dy[i] != 0);
		b[i] = y[i] / dy[i];
		for(int k = 0; k < m; k++){
			A(i, k) = fs[k](x[i]) / dy[i];
		}
	}

	qr decomp(A);
	return decomp.solve(b);
}
} // namespace pp
