#include <iostream>
#include <cmath>
#include "ode.hpp"

// This block of code was generated by Chat GPT Instant 5.3

int main(){

	const double b = 0.25;
	const double c = 5.0;

	auto pendulum = [b, c](double /*t*/, pp::vector y){
		double theta = y[0];
		double omega = y[1];

		pp::vector dydt(2);
		dydt[0] = omega;
		dydt[1] = -b * omega - c * std::sin(theta);

		return dydt;
	};

	pp::vector y0 = {M_PI - 0.1, 0.0};

	auto [ts, ys] = pp::driver(pendulum, 0.0, 10.0, y0, 0.05, 1e-5, 1e-5);

	for(size_t i = 0; i < ts.size(); i++){
		std::cout << ts[i] << " " << ys[i][0] << " " << ys[i][1] << "\n";
	}
	return 0;
}
