#include <iostream>
#include <cmath>
#include "ode.hpp"

// This block was generated by Chat GPT Instant 5.3

void solve_orbit(double eps, double uprime0, const std::string& filename){
	auto orbit = [eps](double /*phi*/, pp::vector y){
		pp::vector dydphi(2);

		double u = y[0];
		double up = y[1];

		dydphi[0] = up;
		dydphi[1] = 1 + eps*u*u - u;

		return dydphi;
	};

	pp::vector y0 = {1.0, uprime0};

	double phimin = 0.0;
	double phimax = 20.0 * M_PI; 

	auto [phis, ys] = pp::driver(orbit, phimin, phimax, y0, 0.01, 1e-5, 1e-5, 0.02);

	FILE* file = fopen(filename.c_str(), "w");

	for(size_t i = 0; i < phis.size(); i++){
		double phi = phis[i];
		double u = ys[i][0];
		double r = 1.0/u;

		double x = r * std::cos(phi);
		double y = r * std::sin(phi);

		fprintf(file, "%g %g %g %g\n", phi, u, x, y);
	}
	fclose(file);
}

int main(){
	solve_orbit(0.0, 0.0, "orbit_circular.txt");
	solve_orbit(0.0, -0.5, "orbit_ellipse.txt");
	solve_orbit(0.01, -0.5, "orbit_precession.txt");

	return 0;
}
