# This block of code was generated by Chat GPT Instant 5.3

import scipy.integrate as integrate
import math

def count_calls(f):
    calls = {"n": 0}
    def wrapper(x):
        calls["n"] += 1
        return f(x)
    return wrapper, calls

tests = [
    ("1/sqrt(x)", lambda x: 1/math.sqrt(x), 0, 1, 2),
    ("log(x)/sqrt(x)", lambda x: math.log(x)/math.sqrt(x), 0, 1, 4),
    ("esp(-x*x)", lambda x: math.exp(-x*x), -math.inf, math.inf, math.sqrt(math.pi)),
]

for name, f, a, b, exact in tests:
    wrapped, calls = count_calls(f)
    result, error = integrate.quad(wrapped, a, b, epsabs=1e-6, epsrel=1e-6)

    print(name)
    print("result =", result)
    print("exact  =", exact)
    print("error  =", abs(result - exact))
    print("calls  =", calls["n"])
    print()