#include<iostream>
#include<string>
#include<cstdlib>
#include<tuple>
#include<fstream>
#include<cmath>
#include<algorithm> // Raptor mini
#include<iomanip>
#include"matrix.hpp"
#include"eigen.hpp"

namespace {

// this block of code was generated by Raptor mini

double exact_energy(int k){
	return -0.5 / double((k + 1) * (k + 1));
}

double analytic_wave(int k, double r){
	if(k == 0) return 2.0 * r * std::exp(-r);
	if(k == 1) return 1.0 / (2.0 * std::sqrt(2.0)) * r * (2.0 - r) * std::exp(-r / 2.0);
	return 0.0;
}

std::pair<pp::vector, pp::matrix> sort_eigenpairs(pp::vector e, pp::matrix V){
	int n = e.size();
	for(int j = 0; j < n - 1; j++){
		int min = j;
		for(int k = j + 1; k < n; k++){
			if(e[k] < e[min]) min = k;
		}
		if(min != j){
			std::swap(e[j], e[min]);
			for(int i = 0; i < n; i++){
				std::swap(V(i, j), V(i, min));
			}
		}
	}
	return {std::move(e), std::move(V)};
}

}

// Task B. Build and diagonalize H
// This block of code was realized by Chat GPT Instant 5.3

int main(int argc, char** argv){
	double rmax = 20.0;
	double dr = 0.1;

	for(int i = 1; i < argc; i++){
		std::string arg = argv[i];
		if(arg == "-rmax" && i + 1 < argc) rmax = std::atof(argv[++i]);
		else if(arg == "-dr" && i + 1 < argc) dr = std::atof(argv[++i]);
	}

	int npoints = (int)(rmax / dr) - 1;
	if(npoints <= 0){ // Raptor mini
		std::cerr << "Invalid grid: rmax=" << rmax << " dr=" << dr << "\n";
		return 1;
	}

	pp::vector r(npoints);
	for(int i = 0; i < npoints; i++) r[i] = dr * (i + 1);

	pp::matrix H(npoints, npoints);
	for(int i = 0; i < npoints - 1; i++){
   		H(i, i)  = -2 * (-0.5 / dr /dr); // Chat GPT Instant 5.3
   		H(i, i + 1) = 1 * (-0.5 / dr / dr); // Chat GPT Instant 5.3
   		H(i + 1, i) = 1 * (-0.5 / dr / dr); // Chat GPT Instant 5.3
	}
	H(npoints - 1, npoints - 1) = -2.0 * (-0.5 / dr / dr);
	for(int i = 0; i < npoints; i++) H(i, i) += -1.0 / r[i];

	auto [e, V] = pp::jacobi(H); // e: eigenvalues, V: eigenvectors
	auto [e_sorted, V_sorted] = sort_eigenpairs(e, V);

	std::cout << std::setprecision(12);
	std::cout << "computed eigenvalues (sorted):\n";
	for(int i = 0; i < std::min(6, (int)e_sorted.size()); i++){
		double exact = exact_energy(i);
		std::cout << i << " " << e_sorted[i]
		          << " exact=" << exact
		          << " delta=" << (e_sorted[i] - exact)
		          << "\n";
	}

	double eps0 = e_sorted[0]; // Raptor mini
	std::cout << "eps0=" << eps0 << " error=" << (eps0 + 0.5) << "\n"; // Raptor mini

	double normalization = 1.0 / std::sqrt(dr);
	for(int k = 0; k < 2; k++){
		std::string filename = "wavefunc_" + std::to_string(k) + ".dat";
		std::ofstream fout(filename);
		if(!fout){
			std::cerr << "Failed to open " << filename << " for writing\n";
			return 1;
		}
		fout << std::setprecision(12); // Raptor mini
		for(int i = 0; i < npoints; i++){
			double ri = r[i];
			double fnum = V_sorted(i, k) * normalization;
			double fans = analytic_wave(k, ri);
			fout << ri << " " << fnum << " " << fans << "\n";
		}
		std::cout << "wrote " << filename << "\n";
	}

	return 0;
}
