#include<iostream>
#include<cstdlib>
#include"eigen.hpp"

// Task A, 3. This is a test file in order to verify V^T*A*V = D, V*D*V^T = A, V^T*V = 1, 
// and V*V^T = 1, where A is a random symmetric matrix, V is the orthogonal matrix of 
// eigenvectors, and D is the diagonal matrix with corresponding eigenvalues
// This block of code was generated by Chat GPT Instant 5.3

pp::matrix diag(const pp::vector& w){
	int n = w.size();
	pp::matrix D(n, n);
	for(int i = 0; i < n; i++){
		for(int j = 0; j < n; j++){
			D(i, j) = (i == j ? w[i] : 0.0);
		}
	}
	return D;
}

pp::matrix random_smatrix(int n){
	pp::matrix A(n, n);
	for(int i = 0; i < n; i++){
                for(int j = i; j < n; j++){
			double x = double(std::rand()) / RAND_MAX;
			A(i, j) = x;
			A(j, i) = x;
		}
	}
	return A;
}

bool approx(const pp::matrix& A, const pp::matrix& B, double acc=1e-6, double eps=1e-6){
	if(A.size1() != B.size1() || A.size2() != B.size2()) return false;
	for(int i = 0; i < A.size1(); i++)
		for(int j = 0; j < A.size2(); j++)
			if(!pp::approx(A(i, j), B(i, j), acc, eps)) return false;
	return true;
}

int main(){
	int n = 5;
	pp::matrix A = random_smatrix(n);

	auto [w, V] = pp::jacobi(A);
	pp::matrix D = diag(w);

	pp::matrix VTAV = V.T() * A * V;
	pp::matrix VDVT = V * D * V.T();

	pp::matrix I1 = V.T() * V;
	pp::matrix I2 = V * V.T();

	pp::matrix I(n, n);
	I.setid();

	std::cout << "VTAV == D    : " << approx(VTAV, D) << "\n";
        std::cout << "VDVT == A    : " << approx(VDVT, A) << "\n";
        std::cout << "VTV == I    : " << approx(I1, I) << "\n";
        std::cout << "VVT == I    : " << approx(I2, I) << "\n";

	return 0;
}
